### PR TITLE
keygen: Fix public key comment

### PR DESCRIPTION
**Pull request by stigtsp**
- Fix support for adding `-C` to the .pub file
- Set default comment to user@host

### CODE REVIEW

**Comment by Foxboron** [comment]
I was wondering if this should be part of the `Key{}` struct actually.

We never actually read this public key for the agent so running `ssh-tpm-agent` and then `ssh-add -L` won't show the comments, and they should.

**Comment by stigtsp** [comment]
> I was wondering if this should be part of the `Key{}` struct actually.
> 
> We never actually read this public key for the agent so running `ssh-tpm-agent` and then `ssh-add -L` won't show the comments, and they should.

Yes this makes sense, so we can show the comment to Pinentry as well

**Comment by Foxboron** [comment]
@stigtsp Do you want to take a stab at this?

I can write some tests for the key stuff itself so you can more easily extend the struct and parsing.

**Comment by Foxboron** [comment]
Being implemented with this https://github.com/Foxboron/ssh-tpm-agent/pull/18

**Pull request closed without merging**
